server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        label: master
        git:
          uri: file:///D:/Git/SpringConfig/springcloudConfig # git仓库的地址
#          skipSslValidation: true
#          search-paths: /**  # git仓库地址下的相对地址，可以配置多个，用,分割。
#          username: chenqiwei
#          password: Chen123456...





#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    register-with-eureka: false
    fetch-registry: false
